Added xmlrpc dependency for ruby >= 2.4.0 support
zachfeldman/rubypress pull request #55
Opened 2017-02-17 10:30 UTC by rimkashox

Hey man, that's the only change needed and it works well on 2.4.0.

2017-02-17 16:28 UTC, zachfeldman commented
Very cool. Would you mind also doing a version bump and adding yourself to the contributors list? Then I'll redeploy to Rubygems so we can support 2.4.0!

Thanks again @rimkashox .

2017-02-17 23:29 UTC, rimkashox commented
My pleasure @zachfeldman!

2017-02-18 19:53 UTC, zachfeldman requested changes
Sorry, just a few minor edits needed before merge.

2017-02-18 19:53 UTC, zachfeldman commented on README.md
> +
I'm seeing a lot of extra details in this commit, mind removing these?

2017-02-18 19:53 UTC, zachfeldman commented on README.md
> +* Karim Naufal [@mcoyler](https://github.com/rimkashox) (Added support for Ruby >= 2.4.0)
Almost there, you stole @mcoyler 's username!

2017-02-18 19:53 UTC, zachfeldman commented on rubypress.gemspec
> +  s.version = '1.2.2'
Good

2017-02-18 23:35 UTC, rimkashox commented on README.md
> +
Hey man, this must be my atom text editor that's doing some automatic fixing of blank lines (it's the editor from Github, just an amazing piece of code). I didn't manually do anything, and if you look at it carefully, you will see that nothing really happens.

2017-02-18 23:35 UTC, rimkashox commented on rubypress.gemspec
> +  s.version = '1.2.2'
👍🏻

2017-02-24 13:30 UTC, rimkashox commented
Zach, all should be good now, no? Would really be cool to have the Rubypress fully compatible with 2.4.0... I really don't care about having my name in the readme, tell me if you'd like me to revert this change!

2017-02-24 15:28 UTC, zachfeldman commented on README.md
> +
Sure, I use Atom too. I'll ignore this for now but I'd advise you to watch out for projects that are more strict on commits!

2017-02-24 15:29 UTC, merged